import React from 'react';
import { Col, CardBody, Card } from 'reactstrap';
import { MDBDataTable } from 'mdbreact';
import '../Controle/datacontrole.scss';
import BtnExportData from '../Controle/BtnExportData';

const ProgramData = () => {
  const data = {
    columns: [
      {
        label: 'Number',
        field: 'number',
        sort: 'asc',
      },
      {
        label: 'Label',
        field: 'label',
        sort: 'asc',
      },
      {
        label: 'Price Net',
        field: 'price_net',
        sort: 'asc',
      },
      {
        label: 'Family',
        field: 'family',
        sort: 'asc',
      },
      {
        label: 'Group',
        field: 'group',
        sort: 'asc',
      },
      {
        label: 'TVA',
        field: 'tva',
        sort: 'asc',
      },
      {
        label: 'Sub Family',
        field: 'sub_family',
        sort: 'asc',
      },
      {
        label: 'Family Num',
        field: 'family_num',
        sort: 'asc',
      },
      {
        label: 'Group Num',
        field: 'group_num',
        sort: 'asc',
      },
      {
        label: 'Sub Family Num',
        field: 'sub_family_num',
        sort: 'asc',
      },
      {
        label: 'TVA Num',
        field: 'tva_num',
        sort: 'asc',
      },
      {
        label: 'Price TTC',
        field: 'price_ttc',
        sort: 'asc',
      },
      {
        label: 'Price Net HT',
        field: 'price_net_ht',
        sort: 'asc',
      },
      {
        label: 'Price HA HT',
        field: 'price_ha_ht',
        sort: 'asc',
      },
      {
        label: 'Provider',
        field: 'provider',
        sort: 'asc',
      },
    ],
    rows: [
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
      {
        number: '457',
        label: 'FORMULE PT DEJ',
        price_net: '8.00',
        family: 'BAR',
        group: 'SOLIDES 10%',
        tva: 'TVA 10.00 %',
        sub_family: 'SOUS FAMILLE 0',
        family_num: '15',
        group_num: '2',
        sub_family_num: '0',
        tva_num: '3',
        price_ttc: '20.00',
        price_net_ht: '18.18',
        price_ha_ht: '0',
        provider: 'Provider',
      },
    ],
  };

  return (
    <Col lg={12}>
      <Card>
        <CardBody>
          <h3 className="text-center">Programmation</h3>
          <BtnExportData />
          <MDBDataTable responsive bordered data={data} />
        </CardBody>
      </Card>
    </Col>
  );
};

export default ProgramData;
