export const SINGLE_RESTAURANT_REQUEST = 'SINGLE_RESTAURANT_REQUEST';
export const SINGLE_RESTAURANT_SUCCESS = 'SINGLE_RESTAURANT_SUCCESS';
export const SINGLE_RESTAURANT_FAIL = 'SINGLE_RESTAURANT_FAIL';
//export const SINGLE_RESTAURANT_RESET = 'SINGLE_RESTAURANT_RESET';
